name: terraform

on:
  push:
    paths:
      - 'terraform-examples/*'
    branches:
      - main

jobs:
  tf-apply:
    name: Deploy Boards and Queries
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-examples
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Set Honeycomb API Key environment variable
        run: echo "HONEYCOMB_API_KEY=${{ secrets.HONEYCOMB_API_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
